### ISSUE TITLE
commentChar=auto not supported

### ISSUE THREAD

**Issue by zaquestion** [zaquestion/lab#8]
https://github.com/github/hub/issues/1512 is definitely also an issue in lab.

**Comment by mareksuscak** [comment]
the issue has been resolved in hub, check out the changeset here: https://github.com/github/hub/pull/1660

**Comment by bmeneguele** [comment]
Considering the way `lab` works today, I'm kinda skeptical it's still a problem for us.
@zaquestion any thoughts? I'm inclined to close it.

**Comment by zaquestion** [comment]
I wouldn't be surprised if this is still an issue. That said I think the bigger/more important update to make is https://github.com/zaquestion/lab/issues/334
